### PR TITLE
chore: Update bitflags from 1.3.x to 2.x

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by Martin1887** [comment]
Thanks!

**Comment by smoelius** [comment]
Would it be possible to get a release with this change?

**Comment by Martin1887** [comment]
Hello, the 0.10 release with this and many other changes will be released soon (this time is true :-)).

**Comment by Martin1887** [comment]
The 0.9.4 version has just been released.

**Comment by smoelius** [comment]
Thanks!

**Comment by Martin1887** [comment]
Release 0.9.4 has been yanked and 0.9.5 has just been released due to a bug (#831).

**Comment by smoelius** [comment]
Thanks for your diligence, @Martin1887!

**Comment by Martin1887** [comment]
0.9.6 just released updating Cargo.lock to fix #833.

**Pull request merged**
