### PR TITLE
Implement table extension for new_algo

### PR DESCRIPTION
**Pull request by marcusklaas**
It currently fails almost all table tests in our suite, but I believe that's only because it expects `<td>`s in table headers whereas this currently produces `<th>`s.

Relevant issue: https://github.com/raphlinus/pulldown-cmark/issues/188

### CODE REVIEW

**Comment by marcusklaas** [comment]
@raphlinus I'd like to add the GFM table tests to the repo, but it seems that the python scripts that generates the tests from the spec is not part of the repository.. is this hosted somewhere else?

**Comment by ScottAbbey** [comment]
I think the test files are created by a build.rs file, not a Python script.

**Comment by raphlinus** [comment]
Oops, for some reason I missed that this is in the review queue, I'll get to it soon. Yes, tests are generated by `build.rs`.

**Comment by marcusklaas** [comment]
I added the table tests generated from GFM's spec and there are some legitimate failures. I'll try to fix those first :-)

**Comment by marcusklaas** [comment]
Note: this is still not ready, but it shouldn't be too long anymore. Normalization of whitespace inside tables and normalization of th elements is done. I'll send you the batsignal when this is ready for a review ^^

**Comment by marcusklaas** [comment]
This is ready for review now!

It passes all GFM's table tests. I needed to add some extra normalization, by dropping whitespace from table elements and removing empty tbody's, but I am fairly certain that these operations don't cause any semantic changes to the html.

Concerning commonmark-extra compliance: we pass the tests wherever commonmark-extra and GFM agree. There's two points on which they are irreconcilable: `td` vs `th` in `thead`s and adding filler cells. To pass commonmark-extra's table tests, I've transformed their `td`s to `th`s in the tests and disabled one test that expected no fillers to be added.

**Pull request merged**
