### PR TITLE
Do not %-encode `^` and `~` characters

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
@lilyball gave a very nice explanation on rust repository about this. You can see it [here](https://github.com/rust-lang/rust/issues/97125).

### CODE REVIEW

**Comment by marcusklaas** [comment]
This looks sensible to me. Thanks!

**Comment by GuillaumeGomez** [comment]
Thanks for the quick merge! If you could make a release with this fix whenever you can, it'd be super appreciated too. :)

**Comment by GuillaumeGomez** [comment]
Sorry to ask but do you know when will be the next release? It would allow us to fix this bug: https://github.com/rust-lang/rust/issues/97125. Thanks in advance!

**Comment by marcusklaas** [comment]
We just released [v0.9.2](https://crates.io/crates/pulldown-cmark/0.9.2) that includes your fix.

**Comment by GuillaumeGomez** [comment]
Thanks a lot!

**Pull request merged**
