### PR TITLE
Bump version to 0.9.1

### PR DESCRIPTION
**Pull request by marcusklaas**
Getting ready to do a patch release.

### CODE REVIEW

**Review by raphlinus — COMMENTED** [review]
Update README.md as well?

**Comment by marcusklaas** [comment]
I _always_ forget to update the README, but I think it may not be necessary in this case? It says `0.9`, which should pick up the patch release automatically, right?

**Comment by raphlinus** [comment]
It does if you add it de novo, but won't update an existing lockfile. I personally consider it good practice to include the point, but agree it's not absolutely required.

**Comment by marcusklaas** [comment]
> but won't update an existing lockfile
I did not know this! I will update the README as well.

**Review by raphlinus — APPROVED** [review]

**Comment by marcusklaas** [comment]
@ehuss: we just released a [new version](https://crates.io/crates/pulldown-cmark/0.9.1) which includes a fix for the bug you reported!

**Comment by ehuss** [comment]
Thanks! ❤️

**Pull request merged**
