### PR TITLE
Fix emphasis panics

### LINKED ISSUE #305: Panic on "_**x*0" * 6 (slice index starts at 2 but ends at 1)
```
# slice index starts at 1 but ends at 0
python -c "print('_@__*CDATA[' * 4 + '_')" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('*:A*_*' * 32768)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('*/\x00*_*' * 32768)" | RUST_BACKTRACE=1 cargo run -- -TFSL
# slice index starts at 2 but ends at 1
python -c 'print("_**x*0" * 6)' | RUST_BACKTRACE=1 cargo run
python -c 'print(" _*:**" * 4)' | RUST_BACKTRACE=1 cargo run
python -c 'print("*&*_ *" * 5)' | RUST_BACKTRACE=1 cargo run
python -c "print('_Z**a*' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~\x80*pre_~' * 6)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('a*ð\x90\x80\x80**_' * 6)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('*\xa0_*{*' * 5)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('*/*\r_*' * 5)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('*_0123456789ABCDEF**\x80' * 6)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('X_**9*' * 5)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('*.**\xa0_' * 5)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('**</pre>*_\xa0' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('9*_f**' * 5)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('a*à\xa0\x80_~~' * 6)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('**A_*Z' * 6)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print(' ~~>_*' * 4)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print(']**\r_*' * 5)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('pre_~~à\xa0\x80*' * 5)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('_\r~~*[]' * 5)" | RUST_BACKTRACE=1 cargo run -- -TFSL
# slice index starts at 3 but ends at 2
python -c 'print("_X*__<" * 5)' | RUST_BACKTRACE=1 cargo run
python -c 'print("_a*)**" * 5)' | RUST_BACKTRACE=1 cargo run
python -c 'print(">_~~x*" * 6)' | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('f*</pre>**_' * 7)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~CDATA[\x80_*~' * 7)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('9_;*~~' * 7)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('[^_0*__' * 5)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~~ssse3*`_' * 9)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('address*_=__' * 7)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~~f*)_' * 5)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('*pre_**=' * 5)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('*`**_\x00' * 15)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('*|**a_' * 6)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('_**[*pre' * 8)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('*;*_ssse3*' * 6)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('**:*_\x00' * 8)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('[]_~~\x00*' * 6)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('_~~x0*' * 6)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~pre*!_~' * 7)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~~ssse3*_!--' * 5)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('X_*-~~' * 7)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('addresspre*_~~' * 7)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('[]*X_**' * 5)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~~f*_%' * 5)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('*_x*>*' * 7)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('!*~~pre_' * 6)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('_~~\x80*`' * 11)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~~pre*$_' * 5)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('**_A*!--' * 8)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('*{**_\x80' * 8)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~~A*_{' * 5)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('*_&#x27;~~ssse3' * 8)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('|**_pre*' * 6)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('*{_~~Z' * 8)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('_{~~X*' * 6)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('0123456789ABCDEF*_~~ssse3' * 7)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('9_*[^~~' * 7)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print("__ssse3*_'" * 5)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print("_à\xa0\x80*__'" * 5)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('*?~~\x00_' * 6)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('~x*._~' * 7)" | RUST_BACKTRACE=1 cargo run -- -TFSL
python -c "print('(*à\xa0\x80_**' * 5)" | RUST_BACKTRACE=1 cargo run -- -TFSL
```

```rust
thread 'main' panicked at 'slice index starts at 2 but ends at 1', src/libcore/slice/mod.rs:2419:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::slice::slice_index_order_fail
             at src/libcore/slice/mod.rs:2419
   9: <core::ops::range::Range<usize> as core::slice::SliceIndex<[T]>>::index
             at /rustc/befeeb7c083c9e5edddc86563cc461185d897a13/src/libcore/slice/mod.rs:2588
  10: <core::ops::range::RangeFrom<usize> as core::slice::SliceIndex<[T]>>::index
             at /rustc/befeeb7c083c9e5edddc86563cc461185d897a13/src/libcore/slice/mod.rs:2671
  11: core::slice::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/befeeb7c083c9e5edddc86563cc461185d897a13/src/libcore/slice/mod.rs:2396
  12: <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index
             at /rustc/befeeb7c083c9e5edddc86563cc461185d897a13/src/liballoc/vec.rs:1677
  13: pulldown_cmark::parse::InlineStack::find_match
             at src/parse.rs:1505
  14: pulldown_cmark::parse::Parser::handle_emphasis
             at src/parse.rs:2048
  15: pulldown_cmark::parse::Parser::handle_inline
             at src/parse.rs:1786
  16: <pulldown_cmark::parse::Parser as core::iter::traits::iterator::Iterator>::next
             at src/parse.rs:2419
  17: <&mut I as core::iter::traits::iterator::Iterator>::next
             at /rustc/befeeb7c083c9e5edddc86563cc461185d897a13/src/libcore/iter/traits/iterator.rs:2693
  18: pulldown_cmark::html::HtmlWriter<I,W>::run
             at ./src/html.rs:144
  19: pulldown_cmark::html::write_html
             at ./src/html.rs:522
  20: pulldown_cmark::main
             at src/main.rs:260
  21: std::rt::lang_start::{{closure}}
             at /rustc/befeeb7c083c9e5edddc86563cc461185d897a13/src/libstd/rt.rs:64
  22: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  23: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  24: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  25: std::rt::lang_start
             at /rustc/befeeb7c083c9e5edddc86563cc461185d897a13/src/libstd/rt.rs:64
  26: main
  27: __libc_start_main
  28: _start
```

### PR DESCRIPTION
**Pull request by marcusklaas**
This fixes #305 and #306. Ran the fuzzer for a few million patterns and no panics/ superlinear behaviors came up!

### CODE REVIEW

**Comment by dimbleby** [comment]
Even with this fix , 

```
    #[test]
    fn another_emphasis_panic() {
        parser_with_extensions("*__#_#__*").count();
    }
```

gives `thread 'parse::test::new_issue' panicked at 'unexpected item body MaybeEmphasis(1, true, false)', src/parse.rs:2413:14`.  

That looks a lot like #306, which is why I mention it here, but perhaps it wants a new issue?

(I [previously said](https://github.com/raphlinus/pulldown-cmark/issues/311#issuecomment-491206974) I wasn't going to pursue the fuzzing, but I saw all the recent fixes and got to wondering whether this was really ready to see off the fuzzer...  It found this fairly quickly.)

**Comment by dimbleby** [comment]
Maybe

```patch
-            self.set_lowerbound(c, count, both, self.stack.len().saturating_sub(1));
+            self.set_lowerbound(c, count, both, lowerbound);
```

??

which does fix the panic and doesn't obviously break anything, but I am very much guessing here without having any real idea what the code is doing!

**Comment by marcusklaas** [comment]
Wow, that actually makes a lot of sense. Thanks!!

Guess it pays off to run a fuzzer for a bit. I'll try to reproduce your setup and find more bugs :-)

**Comment by marcusklaas** [comment]
Aaah, I think I finally found the bug! When searching something in a subslice, it will give you the index for that subslice and not the entire vector.

**Comment by marcusklaas** [comment]
Raph! You're back!

Thanks for the review :-)

**Pull request merged**
