### PR TITLE
Ignore the benchmarks

### PR DESCRIPTION
**Pull request by dns2utf8**
So it can be published on crates.io

cc: @GuillaumeGomez

### CODE REVIEW

**Comment by dns2utf8** [comment]
Enables https://github.com/rust-lang/rust/pull/65894

**Comment by marcusklaas** [comment]
It seems we can keep the benchmarks if we remove it from the Cargo exclusion list, which seems like a nicer solution. Could you make that change in this PR, then I'll merge it and publish to crates.io.

**Comment by dns2utf8** [comment]
I can do that.
On the other hand, why does the released version need the benchmark code?

**Comment by marcusklaas** [comment]
Because the code commented out refers to benchmarks, but when they are excluded from the crate they cannot be found and it blocks the publication.

**Comment by dns2utf8** [comment]
It seems that it is currently not possible to release a package without the benchmark code included.
Even if that code is not touched during build later.

**Comment by marcusklaas** [comment]
Yup, seems that way. The current 0.6.1 release was done by including the benchmark code.

Thanks for your PR. If we find a way to exclude the benchmarks in the future, then let's revisit the subject.

**Comment by dns2utf8** [comment]
There seems to be a discussion going on about maybe wanting to use included benchmarking code for compiler testing, but I am not sire that is the best idea.
Closing this PR for now. Thank you

**Pull request closed without merging**
