### PR TITLE
Update html5ever to 0.23

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by marcusklaas** [comment]
There are some test failures with this update. It appears some behavior changed. We may need to adjust our usage to accomodate. Is this something you could look into?

**Comment by ignatenkobrain** [comment]
Oh, I did simple `cargo test` on my laptop and it worked without any problems...

I'm not expert in this html/markup5ever things.. I would appreciate if you could help me with that.

**Comment by ignatenkobrain** [comment]
So I checked and it happens due to this commit: https://github.com/servo/html5ever/commit/8bf65ef61daf612a3b4d7e6007fde7297d6210eb

**Comment by marcusklaas** [comment]
Did you identify that commit using a git-bisect? It's not immediately clear to me how that influences its behavior...

**Comment by ignatenkobrain** [comment]
Yes.

**Comment by marcusklaas** [comment]
Ok, so the commit you linked actually had all the answers in its comments :grimacing:

Apparently `RcDom` drops all its nodes now when it is dropped itself. The solution is trivial: only drop it when we are done. Making `normalize_dom` accept a reference [here](https://github.com/raphlinus/pulldown-cmark/blob/master/tests/lib.rs#L73) does the trick.

**Comment by marcusklaas** [comment]
html5ever was upgrading in the 0.5.1 release. Thanks for the PR though :-)

**Pull request closed without merging**
