### PR TITLE
Add Travis CI directives and badge

### PR DESCRIPTION
**Pull request by nelsonjchen**
Closes https://github.com/google/pulldown-cmark/issues/79

### CODE REVIEW

**Comment by polyzen** [comment]
Beat me to it! Looks like you opened #112 accidentally.

**Comment by nelsonjchen** [comment]
@polyzen That's intentional and for a forward branch. I didn't see any ports of stuff like documentation updates yet and whatnot merged or rebased into `new_algo` so I opened a separate PR.

**Comment by polyzen** [comment]
You may want to add `cache: cargo`.

**Comment by nelsonjchen** [comment]
Probably superseded.

**Pull request closed without merging**
