### PR TITLE
Simplify Html and Options

### PR DESCRIPTION
**Pull request by marcusklaas**
Removes some unused and unnecessary code. This is a breaking change.

### CODE REVIEW

**Comment by Keats** [comment]
While you're doing breaking changes, you might consider renaming Header -> Heading?
See the comment by @chris-morgan https://github.com/getzola/zola/pull/685#issuecomment-493488879 and http://altformat.org/index.asp?id=5&pid=389&ipname=GB

**Comment by marcusklaas** [comment]
I am all for it!

**Comment by marcusklaas** [comment]
The zola people were the ones who suggested this ;-) But it would definitely be helpful to get more feedback.

**Comment by GuillaumeGomez** [comment]
Looks good to me as well! :+1:

**Pull request merged**
