### PR TITLE
Add task list with a list item's first paragraph

### PR DESCRIPTION
**Pull request by marcusklaas**
Fixes https://github.com/raphlinus/pulldown-cmark/issues/557.

### CODE REVIEW

**Comment by andogq** [comment]
Just wondering if there's any update on this PR, would love to see it merged!

**Comment by tvanderstad** [comment]
My team is using your crate to build a markdown note-taking app and ran into this issue; would love to see this PR merged!

**Comment by Martin1887** [comment]
This will be included in the next release.

**Comment by tvanderstad** [comment]
👏

**Pull request merged**
