### PR TITLE
Autolink fixes

### PR DESCRIPTION
**Pull request by marcusklaas**
Addresses https://github.com/raphlinus/pulldown-cmark/issues/382 and https://github.com/raphlinus/pulldown-cmark/issues/381.

This PR should also fix any scans beyond block ends of other inline items.

Many thanks to @mity for the excellent bug reports!

### CODE REVIEW

**Comment by mity** [comment]
The commit message "Don't allow ascii whitspace at end of autolink" makes me wonder whether it is good enough. CommonMark specs bans whitespace (as well as control chars) anywhere in the URI, so `<http://foo bar>` shouldn't be autolink too.

Even if you want to allow URIs with spaces in them, it should imho still at least also ban the control chars at the end of it.

**Comment by marcusklaas** [comment]
Oh, sorry for the confusion. You're absolutely right that ascii whitespace is not allowed anywhere in the autolink. That was already mostly working, with only whitespace at the end being (incorrectly!) accepted by pulldown. That commit fixed that last case. Hope this clears it up!

**Comment by mity** [comment]
Ok. Sorry for false alarm then. 

And the control char rule as e.g. for `<http://\a>` (in C string notation)?

**Comment by marcusklaas** [comment]
Any [whitespace character](https://spec.commonmark.org/0.29/#whitespace-character) will cause the autolink to be rejected, including `U+000A`. Is that what you meant?

**Comment by mity** [comment]
No. C esq. seq. '`\a`' is `U+0007` (known also as alert or bell char, used in ancient times to make a terminal beep if it supported it), not `U+000A`. It is ASCII conttol char (as any with a codepoint lower then 32) but it is not a whitespace.

**Comment by marcusklaas** [comment]
Aaaah, I may have incorrectly removed that bit :fearful: 

Excellent catch! Thank you for your vigilance ;-) I'll correct this immediately.

**Pull request merged**
