### PR TITLE
Issue 430

### PR DESCRIPTION
**Pull request by marcusklaas**
Addresses https://github.com/raphlinus/pulldown-cmark/issues/430.

### CODE REVIEW

**Comment by Gozala** [comment]
I'm noticing that this had being around since February. Does it needs more work before it can be merged it ?

**Comment by marcusklaas** [comment]
I think it's ready to go, just needs a review.

@raphlinus, do you have time for this?

**Comment by alerque** [comment]
I was about to try to hack around this downstream ... it would be really nice to see this merged.

**Comment by alerque** [comment]
I've compiled this PR and checked it against what I expected the ranges to be and it is now returning end bytes for Reference links similar to the way Inline links currently work. I can't speak for every possible scenario but at least that bit seems right here.

**Comment by marcusklaas** [comment]
Cool, thanks for doing a testrun @alerque! Let us know if you find any other issues :-)

**Pull request merged**
