### PR TITLE
Extensible rendering prototype

### PR DESCRIPTION
**Pull request by marcusklaas**
This implements a prototype of option 3 listed in https://github.com/raphlinus/pulldown-cmark/issues/116. It allows for users to define their own custom rendering for a selection of events and/ or tags. This should add the required flexibility to address many use cases without having to account for them all in pulldown-cmark itself, keeping the implementation lean and fast.

An example inline HTML stripper use case could look like this:
```rust
use pulldown_cmark::{html, Parser, Event, Tag};

let markdown_str = "No html!<foo>";
let mut html_buf = String::new();
let parser = Parser::new(markdown_str);

html::push_html_with_extension(&mut html_buf, parser, |state, event| {
    if let Event::InlineHtml(..) = event {
        Ok(state.write("<REDACTED>"))
    } else {
        // default rendering
        Err(event)
    }
});

assert_eq!(&html_buf[..], "<p>No html!<REDACTED></p>\n");
```

The overhead for adding custom rendering would be fairly small and none if it's not used.

Paging issues https://github.com/raphlinus/pulldown-cmark/pull/103, https://github.com/raphlinus/pulldown-cmark/issues/116, https://github.com/raphlinus/pulldown-cmark/issues/142, https://github.com/raphlinus/pulldown-cmark/issues/130 and https://github.com/raphlinus/pulldown-cmark/issues/346.

Paging users @RadicalZephyr, @maghoff, @Inicola, @Keats, @transitracer and @Figments.

Would this cover your use cases? And would such an interface work for you?

### CODE REVIEW

**Comment by marcusklaas** [comment]
OTOH, this may not be better than simply filtering or mapping events of interest to HTML events, since those will be written to the buffer verbatim. :thinking:

**Comment by maghoff** [comment]
Appreciate the initiative :) This looks like the first implementation I had in my branch for HTML-less markup (#103), but it only made me realize that it cannot work.

I'm not looking for a way to secure the input, but rather to change the input language such that HTML tags aren't special at all. The problem is that HTML tags trigger a state change in the parser, so it parses the tags _as HTML_, where I would need it to be parsed as Markdown.

For example, I would want `<a href=\"this *should* be parsed\">Not a link</a>` to cause `should` to be rendered emphasized: `&lt;a href=&quot;this <em>should</em> be parsed&quot;&gt;Not a link&lt;/a&gt;`. See [my test suite](https://github.com/maghoff/pulldown-cmark/blob/master/tests/disable_html.rs) for more examples.

**Comment by marcusklaas** [comment]
Ah yes, it seems that would have to be tackled in the parser indeed. Thanks for elaborating!

**Comment by Keats** [comment]
For #346 it might work but ideally it would be done in pulldown_cmark directly as that seems something common enough that it wouldn't make sense for every user to re-implement it.

**Comment by Figments** [comment]
Yeah, this is something I'm really excited to use. Though, what about modifying existing Markdown syntax, such as `_this_` being an underline rather than emphasis? [Discord does this for multiple tags, on top of extensions.](https://support.discordapp.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-) Would something like this be possible?

**Comment by marcusklaas** [comment]
Yes, that would be possible with this API extension.

**Comment by Figments** [comment]
That's perfect, then. 😄

**Comment by gauravtiwari** [comment]
Hey, @marcusklaas Any plans when this is gonna be in?

**Comment by marcusklaas** [comment]
It's not clear that this is a proper solution as it covers only slightly more use cases than an adapter around the event iterator. Uses like the one described by @maghoff can't be dealt with using this extension. The additional complexity may not be worth it.

I think we need to further others options first before we consider merging this. More input would be useful!

**Comment by Figments** [comment]
Has any progress been made on this front? Sorry if asking this comes across as rude.

**Comment by marcusklaas** [comment]
@Figments don't worry, it's a fair question. There's no recent progress on this, and there is unlikely to be much progress on this in the foreseeable future. This design adds complexity while still not covering all use cases. I think we should stick to the current philosophy of only providing a simple renderer for basic use cases until a design is found that strikes a good balance between complexity and utility. I will close this PR as I think it's a dead end.

Fortunately, it is really easy to either inject HTML events into the stream to do simple rendering extensions or even write a custom renderer. The default renderer is a good example and very succinct!

**Pull request closed without merging**
